# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|

  config.vm.box = "ubuntu/precise64"

  # download and compile Opentracker
  config.vm.provision :shell, :path => "opentracker.sh"

  # port-forwarding isn't enough, the Vagrant guest needs access to your host to access the BT client
  config.vm.network :public_network
end
