# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|

  config.vm.box = "ubuntu/precise64"

  # Load the bootstrap file
  config.vm.provision :shell, :path => "opentracker.sh"

  # Configure port forwarding
#  config.vm.network :forwarded_port, guest: 80, host: 7080
#  config.vm.network :forwarded_port, guest: 6969, host: 6979

  config.vm.network :public_network
end
